import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { useAuth } from "@/lib/auth";
import { AppShell } from "@/components/layout/AppShell";
import { toast } from "sonner";
import {
  PackageOpen,
  Download,
  Eye,
  FileText,
  FileSpreadsheet,
  File,
  Code2,
  FileImage,
  Loader2,
  ExternalLink,
} from "lucide-react";
import { Link } from "@tanstack/react-router";

export const Route = createFileRoute("/generated-files")({
  head: () => ({ meta: [{ title: "Generated Files — FORGE" }] }),
  component: GeneratedFilesRoute,
});

type FileType = "docx" | "xlsx" | "pdf" | "pptx" | "code";

interface GeneratedFile {
  id: string;
  name: string;
  type: FileType;
  size: string;
  generatedAt: string;
  taskId: string;
  taskType: string;
}

const MOCK_FILES: GeneratedFile[] = [
  { id: "f1", name: "Approval_Note_PMP402.docx", type: "docx", size: "48 KB", generatedAt: "2026-08-29 13:41", taskId: "TSK-0039", taskType: "Document Analysis" },
  { id: "f2", name: "Inspection_Note_Flange_07.docx", type: "docx", size: "36 KB", generatedAt: "2026-08-28 15:22", taskId: "TSK-0035", taskType: "Visual Inspection" },
  { id: "f3", name: "Calculation_Sheet_PipeThickness.docx", type: "docx", size: "29 KB", generatedAt: "2026-08-29 11:04", taskId: "TSK-0038", taskType: "Code & Computation" },
  { id: "f4", name: "Engineering_Report_Q3.xlsx", type: "xlsx", size: "124 KB", generatedAt: "2026-08-27 09:15", taskId: "TSK-0033", taskType: "Document Analysis" },
  { id: "f5", name: "Wall_Thickness_Calc.pdf", type: "pdf", size: "88 KB", generatedAt: "2026-08-26 16:50", taskId: "TSK-0031", taskType: "Code & Computation" },
  { id: "f6", name: "pump_analysis.py", type: "code", size: "4 KB", generatedAt: "2026-08-25 14:32", taskId: "TSK-0028", taskType: "Code & Computation" },
  { id: "f7", name: "Safety_Audit_Summary.docx", type: "docx", size: "55 KB", generatedAt: "2026-08-24 10:11", taskId: "TSK-0025", taskType: "Document Analysis" },
  { id: "f8", name: "Maintenance_Report_Aug26.xlsx", type: "xlsx", size: "201 KB", generatedAt: "2026-08-22 08:47", taskId: "TSK-0022", taskType: "Document Analysis" },
];

const FILE_ICONS: Record<FileType, React.ElementType> = {
  docx: FileText,
  xlsx: FileSpreadsheet,
  pdf: File,
  pptx: FileImage,
  code: Code2,
};

const FILE_COLORS: Record<FileType, string> = {
  docx: "text-info border-info/20 bg-info/10",
  xlsx: "text-success border-success/20 bg-success/10",
  pdf: "text-destructive border-destructive/20 bg-destructive/10",
  pptx: "text-primary border-primary/20 bg-primary/10",
  code: "text-muted-foreground border-border bg-surface",
};

function GeneratedFilesRoute() {
  const { isAuthenticated, isLoading } = useAuth();
  const navigate = useNavigate();

  useEffect(() => {
    if (!isLoading && !isAuthenticated) navigate({ to: "/signin" });
  }, [isLoading, isAuthenticated, navigate]);

  if (isLoading) return <div className="flex min-h-screen items-center justify-center bg-background"><Loader2 className="size-6 animate-spin text-primary" /></div>;
  if (!isAuthenticated) return null;

  return (
    <AppShell>
      <GeneratedFilesPage />
    </AppShell>
  );
}

function GeneratedFilesPage() {
  const [typeFilter, setTypeFilter] = useState<FileType | "all">("all");

  const filtered = MOCK_FILES.filter((f) => typeFilter === "all" || f.type === typeFilter);

  const handleDownload = (file: GeneratedFile) => {
    const blob = new Blob([`FORGE — Sovereign AI Workbench\nGenerated File: ${file.name}\nTask: ${file.taskId} · ${file.taskType}\nGenerated: ${file.generatedAt}\n\nThis is a mock deliverable generated by the FORGE prototype.\n`], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = file.name.replace(/\.(docx|xlsx|pdf|pptx)$/, ".txt");
    a.click();
    URL.revokeObjectURL(url);
    toast.success(`Downloaded ${file.name} (mock)`);
  };

  return (
    <div className="mx-auto w-full max-w-6xl px-6 py-8 space-y-6">
      <div>
        <h1 className="font-display text-2xl font-bold tracking-tight text-foreground flex items-center gap-2">
          <PackageOpen className="size-6 text-primary" />
          Generated Files
        </h1>
        <p className="mt-1 text-sm text-muted-foreground">Deliverables and outputs generated by FORGE across all tasks.</p>
      </div>

      {/* Filter */}
      <div className="flex flex-wrap gap-1.5">
        {(["all", "docx", "xlsx", "pdf", "code"] as const).map((t) => (
          <button
            key={t}
            onClick={() => setTypeFilter(t)}
            className={`rounded-full border px-3 py-1 text-[12px] font-medium transition-colors ${
              typeFilter === t
                ? "border-primary/40 bg-primary/15 text-primary"
                : "border-border text-muted-foreground hover:border-primary/20 hover:text-foreground"
            }`}
          >
            {t === "all" ? "All files" : t.toUpperCase()}
          </button>
        ))}
      </div>

      <p className="text-sm text-muted-foreground">{filtered.length} file{filtered.length !== 1 ? "s" : ""}</p>

      {/* File Cards */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {filtered.map((file) => {
          const FileIcon = FILE_ICONS[file.type];
          const fileColor = FILE_COLORS[file.type];
          return (
            <div key={file.id} className="group rounded-xl border border-border bg-card/70 p-4 space-y-3 hover:border-primary/20 transition-colors">
              <div className="flex items-start gap-3">
                <div className={`grid size-10 shrink-0 place-items-center rounded-lg border ${fileColor}`}>
                  <FileIcon className="size-5" />
                </div>
                <div className="min-w-0 flex-1">
                  <p className="truncate text-[13px] font-medium text-foreground">{file.name}</p>
                  <p className="text-[11px] text-muted-foreground">{file.size} · {file.type.toUpperCase()}</p>
                </div>
              </div>

              <div className="text-[11px] text-muted-foreground space-y-0.5">
                <p>Task: <span className="font-mono text-foreground/80">{file.taskId}</span></p>
                <p>{file.taskType} · {file.generatedAt}</p>
              </div>

              <div className="flex items-center justify-between pt-1 border-t border-border">
                <Link
                  to="/tasks"
                  className="inline-flex items-center gap-1 text-[11px] text-muted-foreground hover:text-primary transition-colors"
                >
                  <ExternalLink className="size-3" />
                  View task
                </Link>
                <div className="flex items-center gap-2">
                  <button className="grid size-7 place-items-center rounded-md border border-border text-muted-foreground transition-colors hover:border-border-strong hover:text-foreground" title="Preview">
                    <Eye className="size-3.5" />
                  </button>
                  <button
                    onClick={() => handleDownload(file)}
                    className="inline-flex items-center gap-1.5 rounded-md border border-primary/30 bg-primary/10 px-2.5 py-1 text-[12px] font-medium text-primary transition-colors hover:border-primary/50 hover:bg-primary/20"
                  >
                    <Download className="size-3.5" />
                    Download
                  </button>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {filtered.length === 0 && (
        <div className="py-16 text-center text-muted-foreground">
          <PackageOpen className="mx-auto size-10 mb-3 opacity-40" />
          <p className="text-sm">No generated files found.</p>
        </div>
      )}
    </div>
  );
}
