import { useState } from "react";
import { Check, Download, FileSignature, Loader2, ExternalLink } from "lucide-react";
import { toast } from "sonner";
import { Link } from "@tanstack/react-router";

interface ApprovalNoteProps {
  label: string;
  fileName: string;
}

export function ApprovalNote({ label, fileName }: ApprovalNoteProps) {
  const [state, setState] = useState<"idle" | "working" | "ready">("idle");

  const generate = () => {
    setState("working");
    window.setTimeout(() => setState("ready"), 1600);
  };

  const download = () => {
    const blob = new Blob(
      [
        `FORGE — Sovereign AI Workbench\nDeliverable: ${fileName}\n\nThis is a mocked deliverable generated by the FORGE prototype.\n`,
      ],
      { type: "text/plain" },
    );
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = fileName.replace(/\.docx$/, ".txt");
    a.click();
    URL.revokeObjectURL(url);
    toast.success(`${fileName} downloaded (mock)`);
  };

  if (state === "ready") {
    return (
      <div className="animate-fade-up space-y-2">
        <div className="flex flex-wrap items-center gap-3 rounded-xl border border-success/30 bg-success/8 px-3 py-2.5">
          <Check className="size-4 text-success" />
          <span className="flex-1 text-[13px] text-foreground">
            {fileName} ready
          </span>
          <button
            onClick={download}
            className="inline-flex items-center gap-1.5 rounded-lg border border-border-strong bg-surface-2 px-3 py-1.5 text-xs font-medium text-foreground transition-colors hover:border-primary/40"
          >
            <Download className="size-3.5 text-primary" />
            Download
          </button>
        </div>
        <div className="flex items-center justify-end">
          <Link
            to="/generated-files"
            className="inline-flex items-center gap-1 text-[11px] text-muted-foreground hover:text-primary transition-colors"
          >
            <ExternalLink className="size-3" />
            Open Generated Files
          </Link>
        </div>
      </div>
    );
  }

  return (
    <button
      onClick={generate}
      disabled={state === "working"}
      className="inline-flex items-center gap-2 rounded-lg bg-primary px-3.5 py-2 text-[13px] font-medium text-primary-foreground transition-opacity hover:opacity-90 disabled:opacity-70"
    >
      {state === "working" ? (
        <Loader2 className="size-4 animate-spin" />
      ) : (
        <FileSignature className="size-4" />
      )}
      {state === "working" ? "Generating deliverable…" : label}
    </button>
  );
}
