/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityLogsRouteImport } from './routes/activity-logs'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as GeneratedFilesRouteImport } from './routes/generated-files'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as TasksRouteImport } from './routes/tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityLogsRoute = ActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratedFilesRoute = GeneratedFilesRouteImport.update({
  id: '/generated-files',
  path: '/generated-files',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/generated-files': typeof GeneratedFilesRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/generated-files': typeof GeneratedFilesRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity-logs': typeof ActivityLogsRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/generated-files': typeof GeneratedFilesRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity-logs'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/generated-files'
    | '/knowledge-base'
    | '/settings'
    | '/signin'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity-logs'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/generated-files'
    | '/knowledge-base'
    | '/settings'
    | '/signin'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/activity-logs'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/generated-files'
    | '/knowledge-base'
    | '/settings'
    | '/signin'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityLogsRoute: typeof ActivityLogsRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  GeneratedFilesRoute: typeof GeneratedFilesRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-logs': {
      id: '/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof ActivityLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generated-files': {
      id: '/generated-files'
      path: '/generated-files'
      fullPath: '/generated-files'
      preLoaderRoute: typeof GeneratedFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityLogsRoute: ActivityLogsRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  GeneratedFilesRoute: GeneratedFilesRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
